### ISSUE TITLE
Case-insensitive aliases

### ISSUE THREAD

**Issue by seancpeters** [dotnet/CliCommandLineParser#72] opened 2017-05-01 21:39 UTC
Is there any interest in optionally allowing aliases to be considered case-insensitive? There's been some talk about wanting it in `dotnet new`. I'd be happy to make a PR for this functionality. I know that you have an overall general plan for programmatically exposing more parse options. So I'd definitely want to work with you / follow your ideas for whatever API changes would be needed.

**Comment by jonsequitur** [comment] 2017-05-02 18:38
I haven't heard it raised before.

Would the case-insensitive aliases in `dotnet new` be the template names? These were modeled as commands in the parser configuration in order to have different options per template, correct?

**Comment by seancpeters** [comment] 2017-05-02 21:23
This is a relatively new request for dotnet new.

The case-insensitivity is desired for options on the command. For example if I setup a parser including the option:
```
Create.Option("-h|--help", "Display help", Accept.NoArguments()),
```
then the user could specify any of:
```-h, -H --help, --Help, --HELP, --hElp, etc.```
to indicate that option.

We haven't made a final decision as to whether we want this functionality or not - I'm currently exploring the possibility.

**Comment by seancpeters** [comment] 2017-05-03 01:49
@rehansaeed may have more details on the desire for case insensitive command input options.

**Comment by jonsequitur** [comment] 2017-05-03 02:42
At least for *nix users I think this would be unintuitive. A number of command line tools (including git) have different meanings for the same option letter depending on case.

**Comment by jonsequitur** [comment] 2017-06-01 01:40
@seancpeters, any further thoughts on this? Is this an issue that would still be worth looking into?

**Comment by seancpeters** [comment] 2017-06-01 02:17
I didn't really have any specific thoughts on it.
@ReganSaaed, this was brought up in https://github.com/dotnet/templating/issues/634 - do you have more specific thoughts on case-sensitive parameters for dotnet new ?

**Comment by RehanSaeed** [comment] 2017-06-01 07:48
In `dotnet new` when I specify a symbol, it's usually in title case `MySymbol` because I'm using the symbol in `#if` pre-processor directives and lower case would look weird. Additionally it provides some readability benefit over using a totally lower case value of `mysymbol`.

However, when passing a value for the symbol to `dotnet new`, I realized the name parameter was all lower case and that the symbol name was case sensitive.

`dotnet new mytemplate --name Foo --MySymbol MySymbolValue`

I think the above looks odd and inconsistent. I'd like my symbol to be displayed in title case when I do `dotnet new foo --help` for readability but users shouldn't have to type it in exactly as displayed as that's just painful for no real benefit.

Now I'm not sure if that's a function of `dotnet new` or the command line parser.

**Comment by jonsequitur** [comment] 2017-06-02 15:34
The parser was designed to be case sensitive, so `--mysymbol` will be treated as a different option than `--MySymbol`. (This is because differentiating arguments by case is standard practice for POSIX, mostly due to the expectation of file system case sensitivity on *nix, but even a number of Windows-native command lines have case-sensitive options.) We could potentially revisit this design decision but I think we might also solve this using the existing capability of option aliases, e.g.

```csharp
Create.Option("--MySymbol|--mysymbol", "<help text>")
``` 

This would assume that you would accept supporting just a subset of the possible casing combinations. For example, `--mYsymBOl` might not be valid. 

Assuming you wouldn't want all of the possibilities displayed in help, it would require a small change to `Microsoft.DotNet.Cli.CommandLine` to support hiding specific aliases. (Right now, we only support hiding whole options, which is accomplished by passing an empty help string.)

@seancpeters, I'm also not sure how the template-specific options are configured into the parser by `dotnet new` but there would be some work there as well.

**Comment by seancpeters** [comment] 2017-06-02 17:47
As-is, the template configuration specifies one form of a symbol. The cli host infers a "short version", which is synonymous with the original (long form). The cli-specific host file can specify different values for the long & short forms, which are used instead - it can also indicate there is no short form.

If we wanted to allow multiple forms with different cases, we'd need to allow additional configuration in the host-specific file, which would probably cause breaking changes with existing template configurations. 

It's probably best to stay relatively close to POSIX standards.

@mlorbetske - thoughts?

**Comment by mlorbetske** [comment] 2017-12-21 06:46
I'm inclined to agree that sticking close to the standards is a good default for sure. As far as balancing something that's easy for the user to type vs something that's easily understandable for development time, this is a gap the host file is meant to fill.

Given that we haven't heard feedback on the case sensitivity of these parameters apart from the report that resulted in this issue, I don't think this is a pressing matter - but we may want to keep in mind the possibility of providing a flag on the option setup to indicate that that particular option should accept any case rather than only-as-specified case if it comes up more frequently in the future.

Agree?

**Comment by jonsequitur** [comment] 2017-12-21 19:19
Sounds good. I'll close this until and unless we hear more opinions on it.

**Closed by jonsequitur** 2017-12-21 19:19 UTC
